CREATE TABLE `rec1` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `user_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime COLLATE utf8mb4_general_ci DEFAULT NULL,
  `re1_1_rotating_part` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_rotating_part_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_hsc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_hsc_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_lsc` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_lsc_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_remaining_guarding` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_1_remaining_guarding_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_noise` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_noise_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_temp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_temp_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_seal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_seal_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_level_oil` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_level_oil_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_coupling` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_coupling` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_temp_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_2_temp_b_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_noise` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_noise_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_temp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_temp_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_seal` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_seal_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_level_oli` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_level_oli_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_coupling` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_coupling_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_temp_b` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_3_temp_b_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_temp_fix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_temp_fix_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_temp_free` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_temp_free_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_noise` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_4_noise_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_5_red_boogie` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_5_red_boogie_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_5_guide` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_5_guide_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_6_red_boogie` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_6_red_boogie_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_6_guide` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_6_guide_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_hanger` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_hanger_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_lock` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_lock_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_scrapper` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `re1_7_scrapper_rm` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
)